version: "3"
services:
  node:
    container_name: agendamento-medico
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    image: liviarachelc/medico-mockapi
    ports:
      - "3000:3000"
